services:
  api:
    build: 
      context: ./backend
    image: athreyag4/resume-tailor-backend 
    ports: 
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - resume

volumes:
  postgres-data:

networks:
  resume: